### ISSUE TITLE
Aspects team member application: Asnel Christian

### ISSUE THREAD

**Issue by AsnelChristian** [coala/teams#45]
# Bio

I am Asnel  Christian Ngoulla, a computer science undergraduate student from Cameroon.
I love python, java, machine learning and computer graphics. I am not funny... but i like hanging around with people who are ( ;) like @adtac, @Adrianzatreanu ... :sweat_smile: ).

# coala Contributions so far

I have contributed some codes to coala, coala-bears and coala-utils, and must of what i did had to do with settings, bears and Requirements...

# Road to the Future
I would really love to see the aspects being implemented and used, and what i plan to do is help with their implementation.

# Specific Responsibilities
Writing tests.

**Comment by adtac** [comment]
ack :)

**Comment by adtac** [comment]
wait, this was a core application originally? Didn't realize the title change

**Comment by sils** [comment]
CC @userzimmermann

**Comment by sils** [comment]
@Asnelchristian can we define responsibilities a bit clearer maybe?

**Comment by userzimmermann** [comment]
Hi @Asnelchristian 

Welcome to the team! :) And sorry for the late reply! I just was very busy the last weeks...

@sils The responsibilities actually look very nice, since I don't like writing tests so much ;P

Based on bio and former contributions I think the collaboration will work very well :)
So I must finally update the team description...
